# Generated by Django 5.1.2 on 2024-11-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0146_delete_img44pdf_delete_pdf3home_delete_pdf4home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('staff', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Room_luxury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('type', models.CharField(max_length=200)),
                ('bedroom', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=90)),
                ('kv', models.CharField(max_length=90)),
                ('price1', models.CharField(max_length=90)),
                ('kv1', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('type', models.CharField(max_length=200)),
                ('bedroom', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=90)),
                ('kv', models.CharField(max_length=90)),
                ('price1', models.CharField(max_length=90)),
                ('kv1', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=90)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='media/')),
                ('room_luxury', models.ManyToManyField(to='main.room_luxury')),
                ('room', models.ManyToManyField(to='main.rooms')),
                ('service', models.ManyToManyField(to='main.service')),
            ],
        ),
    ]
