# Generated by Django 5.1.2 on 2024-11-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0150_detailimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_luxury',
            old_name='type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='type',
            new_name='types',
        ),
    ]
