# Generated by Django 5.1.2 on 2024-11-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_rename_type_room_luxury_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.person'),
            preserve_default=False,
        ),
    ]
