# Generated by Django 5.1.2 on 2024-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_department_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
