# Generated by Django 5.1.2 on 2024-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_person_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='images',
            field=models.ManyToManyField(to='main.detailimage'),
        ),
    ]
