# Generated by Django 5.1.2 on 2024-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0156_person_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
