# Generated by Django 5.1.2 on 2024-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_pdfburj_pdftxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('text', models.TextField()),
            ],
        ),
    ]
