# Generated by Django 5.1.2 on 2024-11-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0160_text1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text1',
        ),
    ]
