# Generated by Django 5.1.2 on 2024-11-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_delete_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='textmain',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
