# Generated by Django 5.1.2 on 2024-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_department_textmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='texttitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
